
name: Build app

on: push
  # workflow_dispatch:
  #   inputs:
  #     name:
  #       description: 'Submitter'
  #       required: true
  #       default: 'Sola' 
  #     iqstage:
  #       description: 'Nexus IQ stage'
  #       required: true
  #       default: 'build' 

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Build with Maven
      run: mvn --batch-mode clean package -Dmaven.test.skip=true 
      
    - name: Upload artifact to staging
      run: mkdir staging && cp target/*.jar staging

    - name: What have we got? 
      run: ls -l target/

    # - name: Nexus IQ evaluation
    #   uses: docker://sonatype/nexus-iq-cli
    #   with:
    #     args: -s http://5a0d-31-48-224-44.ngrok.io -a admin:admin123 -i ghaction -t build target/

    - name: Evaluate Sonatype CLI
        id: evaluate
        uses: sonatype/actions/evaluate@v1
        with:
          iq-server-url: https://your.lifecycle.server
          username: ${{ secrets.LIFECYCLE_USERNAME }}
          password: ${{ secrets.LIFECYCLE_PASSWORD }}
          application-id: lifecycle-app
          scan-targets: target/*.jar
      
      # Fetch the SBOM file associated with the previous Sonatype CLI run
      - name: Fetch SBOM
        uses: sonatype/actions/fetch-sbom@v1
        if: ( success() || failure() ) && steps.evaluate.outputs.scan-id
        with:
          iq-server-url: https://your.lifecycle.server
          username: ${{ secrets.LIFECYCLE_USERNAME }}
          password: ${{ secrets.LIFECYCLE_PASSWORD }}
          application-id: lifecycle-app
          scan-id: ${{ steps.evaluate.outputs.scan-id }}
          sbom-standard: cyclonedx
          sbom-version: 1.5
          artifact-name: my-sbom
